### ISSUE TITLE
Does this support the fan controller DW4SF?

### ISSUE THREAD

**Issue by DeeeeLAN** [tabrindle/homebridge-leviton#1]
I didn’t see it in the list and it seems the current plugin is designed around light switches.

**Comment by tabrindle** [comment]
I don't have one of those, but at some point may add it to my collection. PRs welcome if you're interested in adding support.

**Comment by DeeeeLAN** [comment]
Okay, my mom just got one so I might get around to sending a pull request eventually.

**Comment by dtesenair** [comment]
I added support for the DW4SF and submitted a pull request with my updates.  Thanks for writing this homebridge plugin and for allowing me to contribute.

**Comment by tabrindle** [comment]
As soon as I get some free time, I will test this out. I got one purchased and installed, but still have yet to patch my homebridge setup with this code. 

Thanks for the PR!
