### ISSUE TITLE
Configurable logging level - Enhancement Request

### ISSUE THREAD

**Issue by gdavids57** [tabrindle/homebridge-leviton#11]
The current code logs all events at a frequency rate that fills the Homebridge log with many entries, sometimes obscuring other plug-ins' log entries.  Would it be possible to add a configurable logging feature such that one could set a level to only log serious or critical events?

**Comment by tabrindle** [comment]
Published as part of 1.5.0. Use "loglevel" in the config set as "debug", "info", "warn" or "error". info is the default and is much less chatty than before.
