### ISSUE TITLE
Error parsing json from Leviton.com - possible api change?

### ISSUE THREAD

**Issue by Danimal4326** [tabrindle/homebridge-leviton#12]
Please see below:

`
**[4/12/2021, 10:12:25 AM] [homebridge-leviton] error FetchError: invalid json response body at https://my.leviton.com/api/IotSwitches/847012 reason: Unexpected token < in JSON at position 0
    at /usr/local/lib/node_modules/homebridge-leviton/node_modules/node-fetch/lib/body.js:48:31
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  type: 'invalid-json'
}
`

**Comment by Danimal4326** [comment]
Seems to be working after home bridge restart.  I'll keep an eye out on it.

**Comment by tabrindle** [comment]
Thanks for the report - usually `Unexpected token < in JSON at position 0` errors are an API returning XML or HTML when something on the server goes wonky. Not much I can do about that.
