### ISSUE TITLE
Request to add new dimmer model D26HD to index.js

### ISSUE THREAD

**Issue by master-nevi** [tabrindle/homebridge-leviton#13]
Request to add the 2nd generation of the 600W dimmer `D26HD`. It appears to show up as a simple switch instead of a dimmer switch:

![IMG_45FC2276DCBA-1](https://user-images.githubusercontent.com/987706/115998380-c9422000-a59b-11eb-9040-2cde54596f3a.jpeg)

I'm assuming it should be as easy as appending below [this case](https://github.com/tabrindle/homebridge-leviton/blob/f03b3dce391a8549c67307934845cf4fe742a5d7/index.js#L258) :)

**Comment by S1rPsych0** [comment]
Yes, please take a look at correcting the D26HD as a dimmer instead of a switch. I know these dimmers are supposed to work directly with Homekit but i've had no luck getting them to added to Homekit at all without this plug in and Homebridge. With this plugin, they work flawlessly, minus the dimmer capability.

**Comment by adude007** [comment]
> Yes, please take a look at correcting the D26HD as a dimmer instead of a switch. I know these dimmers are supposed to work directly with Homekit but i've had no luck getting them to added to Homekit at all without this plug in and Homebridge. With this plugin, they work flawlessly, minus the dimmer capability.

Here is what I have found works for adding to HomeKit:

1. Factory Reset Switch
2. Delete native homekit accessory if it is there
3. Add switch to Leviton app
4. Add switch to HomeKit by scanning the code that came with the switch


Also, do you know what version of the firmware you are on? I am using 1.2.1 through some beta program. The newer firmware was meant to address connection issues with Orbi systems.
