### ISSUE TITLE
Auto Discovery of Devices Causes Duplicates in Home App for Devices that Support HomeKit natively

### ISSUE THREAD

**Issue by adude007** [tabrindle/homebridge-leviton#15]
Devices that support HomeKit natively are duplicated in the home app when the device is added to via HomeKit and also added to the My Leviton App. My Leviton App is needed to support Alexa support. Benefit of native HomeKit is that when Leviton server has down time automations are unaffected. 

Request to include a toggle in the plugin settings that can be setup to ignore devices with native HomeKit support.

**Comment by adude007** [comment]
I got this working by doing the following.

add this to the config.schema

"homeKitModels": {
        "type": "array",
        "description": "List of models with native HomeKit support to exclude from being added by this plug-in",
        "items": {
          "type": "string"
        }
      }

Within index.js:

After checking for email and password added and modified sections.

    const excludeDevices = config.homeKitModels.map(name => name.toUpperCase())

    // on launch, init api, iterate over new devices
    api.on('didFinishLaunching', async () => {
      this.log('didFinishLaunching')
      const { devices = [], token } = await this.initialize(config)
      devices.forEach((device) => {
        if (!this.accessories.find((acc) => acc.context.device.serial === device.serial)) {
          if (!excludeDevices.includes(device.model)){
          this.addAccessory(device, token)
          }
        }
      })
    })
  }

**Comment by lucanaut** [comment]
Hello thank you for posting this. I’m in the same boat but I don’t have the same coding skills. I’m going to follow your instructions. For confit, where you say “ List of models with native HomeKit support to exclude from being added by this plug-in” do I actually list the models or do I copy that sentence as is? Sorry if that is a ridiculous question. I literally need this plug in for a handful of fan switches but otherwise I would rather use  native support on my other switches.

**Comment by adude007** [comment]
[Files for Leviton.zip](https://github.com/tabrindle/homebridge-leviton/files/6803988/Files.for.Leviton.zip)

I have uploaded a zip file with two files you need to make the modification. One is config.schema and the other is index.js. I use a Mac and don't know if this would look exactly the same on windows. I assume that these two files are the same for windows and Mac. On MacOS with default node.js installation the files are located: /usr/local/lib/node_modules/homebridge-leviton. You would just overwrite the existing files. 

You will also need to update your homebridge config file with the **bold** text below. You can do that through the user interface.
{
            "email": "yourLevitonEmailAddress",
            "password": "YourLevitonPassword",
            "platform": "LevitonDecoraSmart"**,
            "homeKitModels": [
                "d26hd"
            ]**

        }

To add more than one model of switch to exclude but a comma after the " then a new line with the next model in "". 

Once complete restart your home bridge instance. Check logs for the devices that the Leviton plug in detected. You may need to clear cached accessories from home bridge through the settings.

Best of luck to you!

**Comment by lucanaut** [comment]
Thank you! I also run on a Mac so this is perfect.

**Comment by lucanaut** [comment]
Just wanted to check in and let you know it's working great!! Thank you so much again!

**Comment by adude007** [comment]
> Just wanted to check in and let you know it's working great!! Thank you so much again!

You’re welcome. Just keep in mind that if the plugin gets update this modification will get overwritten. The js file I provided may not work depending on what was changed. The config schema should be fine.

**Comment by tabrindle** [comment]
Feel free to make a pull request with this code, and I will add it to the main plugin.
