### ISSUE TITLE
Brightness increase/decrease option for Model D26HD not appearing

### ISSUE THREAD

**Issue by dangathwal** [tabrindle/homebridge-leviton#24]
I am using Leviton model D26HD second gen, but option to increase/decrease the brightness for these dimmers is not showing up in Homekit through this homebridge plugin. I would like to use this plugin instead of standard Leviton Homekit integration because this plugin allows me to directly import any devices which are added to myleviton app into homekit. Whereas if I was to use standard method I will have to scan homekit QR code to import the device. This is an issue since each time something happens to wifi and device needs to be reconfigured in myleviton app the QR code will have to scanned which is hidden behind the switch cover plate.

**Comment by ninjas28** [comment]
It should be fixed in plugin versions >1.2.0
