### ISSUE TITLE
DW15S is a switch only (not dimmable) and should only present with on/off option

### ISSUE THREAD

**Issue by taw123** [tabrindle/homebridge-leviton#3]
Currently DW15S (non-dimmable switch) and DW1KD are presented to HomeKit BOTH as dimmable switches. Per attached screenshots. Also no way found in platform config to override the erroneous behavior since the platform pulls device instantiation from Leviton directly.
![IMG_0391](https://user-images.githubusercontent.com/10588252/90828951-c055cc00-e2f3-11ea-801e-f5caaebe2261.PNG)
![IMG_0392](https://user-images.githubusercontent.com/10588252/90828955-c350bc80-e2f3-11ea-9b66-8bf68f918b0f.PNG)
![IMG_0393](https://user-images.githubusercontent.com/10588252/90828958-c3e95300-e2f3-11ea-874e-29db38fd0293.PNG)

**Comment by tabrindle** [comment]
Cool, thanks for the report. I didn't have this one to test. I can push an update to disable dimmability for this model.

**Comment by taw123** [comment]
Fixed in 1.1.0
